server:
  port: 8080 # portの指定

spring:
  datasource:
    url: jdbc:mysql://localhost/spring_additional2?characterEncoding=UTF-8&serverTimezone=JST&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always #data.sql,schema.sqlを強制読み込み jpa.hibernate.ddl-autoとセットで
    type: com.zaxxer.hikari.HikariDataSource # デフォルト
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
  #    jndi-name: java:hoge/fuga # JNDIを使用する場合
  
# h2に切り替える場合はbuild.gradleの変更も必要　h2ドライバを読み込みrefresh
#  datasource:
#    url: jdbc:h2:mem:test
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#  thymeleaf:
#    cache: false

  devtools:
    restart:
      enabled: true
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none #エンティティからテーブルの自動生成を解除
  flyway:
    enabled: false 
  mail:
    host: smtp.gmail.com
    port: 587
    username: cdta13167@gmail.com
    password: fieldcafe88
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true